### ISSUE TITLE
There was an error creating the workflow

### ISSUE THREAD

**Issue by zeke** [repo-sync/repo-sync#16]
After authenticating and filling out the form, I see the following message:

> There was an error creating the workflow, please manually create it in `zeke/test-private`.

And I see this in the browser console:

```
main.9cb8cd7a.chunk.js:69 Error: 404 error making request put https://api.github.com/repos/zeke/test-private/contents/.github/workflows/repo-sync.yml: "Not Found"
    at new t (Requestable.js:110)
    at Requestable.js:434
```

Here's a screenshot:

<img width="947" alt="Screen Shot 2019-09-09 at 8 09 18 PM" src="https://user-images.githubusercontent.com/2289/64581148-e03bec00-d33d-11e9-8540-80573e2ff192.png">

I will try to recreate this error locally in development.

cc @wei

**Comment by wei** [comment]
It's not a bugi the code. It's an error from the api to create the file. If you inspect the network call, you should see the API call return something about workflow file can not be modified.

**Comment by wei** [comment]
That was indeed the issue. When the file exists, GitHub.js first queries the existing file for a SHA, then sends a PUT request to update the file with a `sha` field [containing the existing blob SHA of the file to be replaced](https://developer.github.com/v3/repos/contents/#create-or-update-a-file). 

It is likely that due to the special permission handling of workflow files internal to GitHub, the SHA is returning Not found resulting in a 404 response for the PUT request. Maybe that's something @zeke you can follow up with?

The fallback isn't terrible, just a one-time copy/paste of the file  😃

**Comment by zeke** [comment]
I agree that the fallback isn't terrible. After having gone through the installation process a few time now, I also think that the manual process is not much more difficult than using the OAuth app. I swapped the order of the manual-vs-automated installation process accordingly in https://github.com/repo-sync/repo-sync/pull/17
